### PR TITLE
added download widget

### PR DESCRIPTION
**Pull request by jaylinski**
Hi!

I added a download widget.
It accepts categories and tags (filters). You can also set the count of downloads.

Please review!
I tried to follow your code style and comment everything as good as possible.

### CODE REVIEW

**Comment by A5hleyRich** [comment]
Thanks for the PR @jaylinski. I'll hopefully get them merged during the next week.

**Comment by A5hleyRich** [comment]
Sorry for the delay on this. I plan to add this to the 1.6 release.

**Comment by jaylinski** [comment]
ok, thx for the update :+1:

**Comment by A5hleyRich** [comment]
New PR raised #118 with a few improvements on top of this PR. Thanks again!

**Pull request closed without merging**
